### ISSUE TITLE
IE 11 Error

### ISSUE THREAD

**Issue by ezzkht** [500tech/angular-tree-component#259]
Angular 4 app works perfectly fine on IE, until the moment I add the angular-tree-component module. I get the below error on IE only. Firefox and chrome work without errors):
![error](https://cloud.githubusercontent.com/assets/7146880/25178047/f3481512-250c-11e7-8dbb-bd0d9890982b.PNG)

Already included all the required shims.
    ```
<script src="node_modules/core-js/client/shim.min.js"></script>

    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
```

Error details:
_Error: (SystemJS) Expected ':'
	SyntaxError: Expected ':'
	   at ZoneDelegate.prototype.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:363:13)
	   at Zone.prototype.run (http://localhost:3000/node_modules/zone.js/dist/zone.js:125:17)
	   at Anonymous function (http://localhost:3000/node_modules/zone.js/dist/zone.js:760:17)
	   at ZoneDelegate.prototype.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:396:13)
	   at Zone.prototype.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:165:21)
	   at drainMicroTaskQueue (http://localhost:3000/node_modules/zone.js/dist/zone.js:593:25)
	   at invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:464:25)
	Evaluating http://localhost:3000/node_modules/angular-tree-component/dist/angular-tree-component.umd.js
	Error loading http://localhost:3000/node_modules/angular-tree-component/dist/angular-tree-component.umd.js as "angular-tree-component" from http://localhost:3000/app/app.module.js
   {
      [functions]: ,
      __proto__: { },
      __zone_symbol__currentTask: { },
      description: "(SystemJS) Expected ':'
	SyntaxError: Expected ':'
	   at ZoneDelegate.prototype.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:363:13)
	   at Zone.prototype.run (http://localhost:3000/node_modules/zone.js/dist/zone.js:125:17)
	   at Anonymous function (http://localhost:3000/node_modules/zone.js/dist/zone.js:760:17)
	   at ZoneDelegate.prototype.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:396:13)
	   at Zone.prototype.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:165:21)
	   at drainMicroTaskQueue (http://localhost:3000/node_modules/zone.js/dist/zone.js:593:25)
	   at invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:464:25)
	Evaluating http://localhost:3000/node_modules/angular-tree-component/dist/angular-tree-component.umd.js
	Error loading http://localhost:3000/node_modules/angular-tree-component/dist/angular-tree-component.umd.js as "angular-tree-component" from http://localhost:3000/app/app.module.js",
      message: "(SystemJS) Expected ':'
	SyntaxError: Expected ':'
	   at ZoneDelegate.prototype.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:363:13)
	   at Zone.prototype.run (http://localhost:3000/node_modules/zone.js/dist/zone.js:125:17)
	   at Anonymous function (http://localhost:3000/node_modules/zone.js/dist/zone.js:760:17)
	   at ZoneDelegate.prototype.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:396:13)
	   at Zone.prototype.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:165:21)
	   at drainMicroTaskQueue (http://localhost:3000/node_modules/zone.js/dist/zone.js:593:25)
	   at invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:464:25)
	Evaluating http://localhost:3000/node_modules/angular-tree-component/dist/angular-tree-component.umd.js
	Error loading http://localhost:3000/node_modules/angular-tree-component/dist/angular-tree-component.umd.js as "angular-tree-component" from http://localhost:3000/app/app.module.js",
      name: "Error",
      originalErr: { },
      originalStack: "Error: (SystemJS) Expected ':'
	SyntaxError: Expected ':'
	   at ZoneDelegate.prototype.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:363:13)
	   at Zone.prototype.run (http://localhost:3000/node_modules/zone.js/dist/zone.js:125:17)
	   at Anonymous function (http://localhost:3000/node_modules/zone.js/dist/zone.js:760:17)
	   at ZoneDelegate.prototype.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:396:13)
	   at Zone.prototype.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:165:21)
	   at drainMicroTaskQueue (http://localhost:3000/node_modules/zone.js/dist/zone.js:593:25)
	   at invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:464:25)
	Evaluating http://localhost:3000/node_modules/angular-tree-component/dist/angular-tree-component.umd.js
	Error loading http://localhost:3000/node_modules/angular-tree-component/dist/angular-tree-component.umd.js as "angular-tree-component" from http://localhost:3000/app/app.module.js
   at ZoneAwareError (ht",
      stack: "(SystemJS) Expected ':'
	SyntaxError: Expected ':'
	   at ZoneDelegate.prototype.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:363:13)
	   at Zone.prototype.run (http://localhost:3000/node_modules/zone.js/dist/zone.js:125:17)
	   at Anonymous function (http://localhost:3000/node_modules/zone.js/dist/zone.js:760:17)
	   at ZoneDelegate.prototype.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:396:13)
	   at Zone.prototype.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:165:21)
	   at drainMicroTaskQueue (http://localhost:3000/node_modules/zone.js/dist/zone.js:593:25)
	   at invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:464:25)
	Evaluating http://localhost:3000/node_modules/angular-tree-component/dist/angular-tree-component.umd.js
	Error loading http://localhost:3000/node_modules/angular-tree-component/dist/angular-tree-component.umd.js as "angular-tree-component" from http://localhost:3000/app/app.module.js",
      zoneAwareStack: "Error: (SystemJS) Expected ':'
	SyntaxError: Expected ':'
	   at ZoneDelegate.prototype.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:363:13)
	   at Zone.prototype.run (http://localhost:3000/node_modules/zone.js/dist/zone.js:125:17)
	   at Anonymous function (http://localhost:3000/node_modules/zone.js/dist/zone.js:760:17)
	   at ZoneDelegate.prototype.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:396:13)
	   at Zone.prototype.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:165:21)
	   at drainMicroTaskQueue (http://localhost:3000/node_modules/zone.js/dist/zone.js:593:25)
	   at invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:464:25)
	Evaluating http://localhost:3000/node_modules/angular-tree-component/dist/angular-tree-component.umd.js
	Error loading http://localhost:3000/node_modules/angular-tree-component/dist/angular-tree-component.umd.js as "angular-tree-component" from http://localhost:3000/app/app.module.js
   at addToError (http:/"
   }_

**Comment by adamkleingit** [comment]
Hi @ezzkht , which version of angular-tree-component are you using?

**Comment by ezzkht** [comment]
I'm using version 3.2.4

**Comment by ezzkht** [comment]
Any updates?

**Comment by AngularTx** [comment]
I am also getting the same error when running the application in IE. Version 3.2.3 . Any solution ?

**Comment by ezzkht** [comment]
Any workaround for this problem ?
I tried all IE shims, but none worked!

**Comment by ezzkht** [comment]
@adamkleingit any suggestion for the problem?
We have a policy at work that only IE is installed on users' machines :(

**Comment by adamkleingit** [comment]
@ezzkht @AngularTx can you try with the latest version - 3.4.0?
It doesn't mention anywhere which line number is the syntax error?

**Comment by AngularTx** [comment]
i am using angular  version 2.4.3. is it OK to use version 3.4.0 of this
component?

**Comment by adamkleingit** [comment]
Yes, just read the breaking changes in the changelog, but there are very few - we try to remain backwards compatible

**Comment by ezzkht** [comment]
With the latest version, I'm getting the error (void 0) is not a function in all browsers (https://github.com/500tech/angular-tree-component/issues/298)
