### ISSUE TITLE
Support useStrict(true) in Mobx

### ISSUE THREAD

**Issue by adamkleingit** [500tech/angular-tree-component#260]

**Comment by jskrzypek** [comment]
I'm not sure this should be closed yet. I added a copy of the `example/cli` at `example/mobx-strict` in my branch here: https://github.com/jskrzypek/angular2-tree-component/tree/example-mobx-strict and changed it to use mobx's `useStrict()` here: https://github.com/jskrzypek/angular2-tree-component/blob/example-mobx-strict/example/mobx-strict/src/main.ts#L7-L9.

I'm seeing this error when trying to expand the `asyncroot` tree collection on the `mobx-strict` example:
```
ERROR Error: Uncaught (in promise): Error: [mobx] Invariant failed: Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action` if this change is intended. Tried to modify: TreeNode@86.children
Error: [mobx] Invariant failed: Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action` if this change is intended. Tried to modify: TreeNode@86.children
    at invariant (mobx.js:2744) [angular]
    at fail (mobx.js:2739) [angular]
    at checkIfStateModificationsAreAllowed (mobx.js:991) [angular]
    at ObservableValue.prepareNewValue (mobx.js:2477) [angular]
    at setPropertyValue (mobx.js:2402) [angular]
    at TreeNode.set [as children] (mobx.js:2373) [angular]
    at TreeNode._initChildren (tree-node.model.js:359) [angular]
    at :4200/vendor.bundle.js:31843:23 [angular]
    at Object.onInvoke (core.es5.js:4125) [angular]
    at Zone.run (zone.js:125) [angular => angular]
    at :4200/polyfills.bundle.js:3623:57 [angular]
    at invariant (mobx.js:2744) [angular]
    at fail (mobx.js:2739) [angular]
    at checkIfStateModificationsAreAllowed (mobx.js:991) [angular]
    at ObservableValue.prepareNewValue (mobx.js:2477) [angular]
    at setPropertyValue (mobx.js:2402) [angular]
    at TreeNode.set [as children] (mobx.js:2373) [angular]
    at TreeNode._initChildren (tree-node.model.js:359) [angular]
    at :4200/vendor.bundle.js:31843:23 [angular]
    at Object.onInvoke (core.es5.js:4125) [angular]
    at Zone.run (zone.js:125) [angular => angular]
    at :4200/polyfills.bundle.js:3623:57 [angular]
    at resolvePromise (zone.js:712) [angular]
    at resolvePromise (zone.js:683) [angular]
    at :4200/polyfills.bundle.js:3623:17 [angular]
    at Object.onInvokeTask (core.es5.js:4116) [angular]
    at ZoneDelegate.invokeTask (zone.js:397) [angular]
    at Zone.runTask (zone.js:165) [<root> => angular]
    at drainMicroTaskQueue (zone.js:593) [<root>]
    at ZoneTask.invoke (zone.js:464) [<root>]
    at timer (zone.js:1540) [<root>]
```

To reproduce pull my branch `example-mobx-strict` branch and run `npm run example:mobxstrict`, then open `localhost:4200`, open the console and expand the `asyncroot`.
