### ISSUE TITLE
(void 0) is not a function

### ISSUE THREAD

**Issue by shefaligupta** [500tech/angular-tree-component#287]
TypeError: (void 0) is not a function at new e (http://localhost:5555/node_modules/angular-tree-component/dist/angular-tree-component.umd.js:5:4404) at new e (http://localhost:5555/node_modules/angular-tree-component/dist/angular-tree-component.umd.js:5:16437) at CompiledTemplate.proxyViewClass.View_ConfigurationComponent0.createInternal (/DashboardModule/ConfigurationComponent/component.ngfactory.js:624:18) at CompiledTemplate.proxyViewClass.AppView.create (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:11878:25) at CompiledTemplate.proxyViewClass.DebugAppView.create (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:12282:48) at View_DashboardComponent1.createInternal (/DashboardModule/DashboardComponent/component.ngfactory.js:16:19) at View_DashboardComponent1.AppView.create (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:11878:25) at View_DashboardComponent1.DebugAppView.create (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:12282:48) at TemplateRef_.createEmbeddedView (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:8897:18) at ViewContainerRef_.createEmbeddedView (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:9117:56) at NgIf.set [as ngIf] (http://localhost:5555/node_modules/@angular/common/bundles/common.umd.js:1801:41) at Wrapper_NgIf.check_ngIf (/CommonModule/NgIf/wrapper.ngfactory.js:18:23) at CompiledTemplate.proxyViewClass.View_DashboardComponent0.detectChangesInternal (/DashboardModule/DashboardComponent/component.ngfactory.js:252:19) at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:12208:18) at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:12355:48)
originalStack
:
(...)
stack
:
(...)

Is anyone facing an issue like this after upgrade?

Thank you

**Comment by shefaligupta** [comment]
resolved by updating zone.js
