### ISSUE TITLE
Nothing works in NG9

### ISSUE THREAD

**Issue by oferw** [500tech/angular-tree-component#791]
Getting this after a angular 9 new project installation,

ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points

Compiling @angular/animations : es2015 as esm2015
Compiling @angular/compiler/testing : es2015 as esm2015
Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @angular/core/testing : es2015 as esm2015
Compiling mobx-angular : module as esm5
Compiling @angular/animations/browser/testing : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/common/testing : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling angular-tree-component : module as esm5
Error: Error on worker #4: Error: Failed to compile entry-point angular-tree-component (module as esm5) due to compilation errors:
node_modules/@angular/common/common.d.ts:115:22 - error NG6002: Appears in the NgModule.imports of TreeModule, but could not be resolved to an NgModule class

115 export declare class CommonModule {
                         ~~~~~~~~~~~~
node_modules/mobx-angular/dist/mobx-angular.d.ts:8:22 - error NG6002: Appears in the NgModule.imports of TreeModule, but could not be resolved to an NgModule class

8 export declare class MobxAngularModule {
                       ~~~~~~~~~~~~~~~~~

    at ClusterWorker.compile (C:\exampler\newMaterial\tree-test9\node_modules\@angular\compiler-cli\ngcc\src\main.js:177:27)
    at Worker.<anonymous> (C:\exampler\newMaterial\tree-test9\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\worker.js:44:42)
    at Worker.emit (events.js:189:13)
    at process.Worker.process.on (internal/cluster/worker.js:28:12)
    at process.emit (events.js:189:13)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at ClusterMaster.onWorkerMessage (C:\exampler\newMaterial\tree-test9\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:158:27)
    at C:\exampler\newMaterial\tree-test9\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:46:95
    at ClusterMaster.<anonymous> (C:\exampler\newMaterial\tree-test9\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:238:57)
    at step (C:\exampler\newMaterial\tree-test9\node_modules\tslib\tslib.js:136:27)
    at Object.next (C:\exampler\newMaterial\tree-test9\node_modules\tslib\tslib.js:117:57)
    at C:\exampler\newMaterial\tree-test9\node_modules\tslib\tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\exampler\newMaterial\tree-test9\node_modules\tslib\tslib.js:106:16)
    at EventEmitter.<anonymous> (C:\exampler\newMaterial\tree-test9\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:232:32)
    at EventEmitter.emit (events.js:189:13)
Compiling @angular/platform-browser/testing : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/platform-browser/animations : es2015 as esm2015
Compiling @angular/router/testing : es2015 as esm2015
Compiling @angular/common/http/testing : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-test9@0.0.0 postinstall: `ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tree-test9@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\oferwa\AppData\Roaming\npm-cache\_logs\2020-02-12T16_59_00_015Z-debug.log

**Comment by rahulroykumar** [comment]
@oferw .. did ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points work for you? It still fails for me without ngcc.config.js.
